GET http://localhost:3000/products

###
GET http://localhost:3000/products/5

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "computer", "price": 999, "description": "you type on it", "image_url": "https://www.computerhope.com/cdn/big/computer.jpg"
}

###
PATCH http://localhost:3000/products/10
Content-Type: application/json

{
  "name": "keyboard", 
  "price": 30, 
  "description": "you type on it", 
  "image_url": "https://resource.logitechg.com/d_transparent.gif/content/dam/gaming/en/products/pro-keyboard/pro-clicky-hero.png"
}

###
DELETE http://localhost:3000/products/11