@jessica_jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjA1MzcyNTF9.FUvtINNB7pL1ZoCGsqwEjUiqxaD-ebEpWHq0ZiFFzLU

@test_jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjA0MDgzNTJ9.RwnG9itfxQVYv8YbsaLwSkhkmvrfxjV_BXXFiJew6UQ

###
GET http://localhost:3000/products.json?category=furniture

###
GET http://localhost:3000/products/10.json

###
POST http://localhost:3000/products.json
Authorization: Bearer {{jessica_jwt}}
Content-Type: application/json

{"name": "comforter", "price": 50, "description": "it covers you.","quantity": 2, "supplier_id": 3}

###
PATCH http://localhost:3000/products/10.json
Content-Type: application/json

{ "image_url2": "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/peripherals/input-devices/dell/keyboards/km3322w/media-gallery/keyboard-mouse-km3322w-gallery-1.psd?fmt=pjpg&pscan=auto&scl=1&hei=402&wid=676&qlt=100,0&resMode=sharp2&size=676,402"}

###
DELETE http://localhost:3000/products/22
Authorization: Bearer {{jessica_jwt}}

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}


### login/session create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
"email": "jessica@jessica.com",
  "password": "password"

}

### orders create
POST http://localhost:3000/orders
Authorization: Bearer {{jessica_jwt}}
Content-Type: application/json


### orders index
GET http://localhost:3000/orders.json
Authorization: Bearer {{jessica_jwt}}

### orders show
GET http://localhost:3000/orders/43.json
Authorization: Bearer {{jessica_jwt}}


### carted_products create(add to cart)
POST http://localhost:3000/carted_products.json
Authorization: Bearer {{jessica_jwt}}
Content-Type: application/json

{"product_id": 23,"quantity": 2}


### carted_products index
GET http://localhost:3000/carted_products.json
Authorization: Bearer {{jessica_jwt}}

### carted_products delete
DELETE http://localhost:3000/carted_products/3
