GET http://localhost:3000/products.json

###
GET http://localhost:3000/products/10.json

###
POST http://localhost:3000/products.json
Content-Type: application/json

{"name": "Lamp", "price": 50, "description": "it gives you lights", "url": "https://www.ikea.com/us/en/images/products/arstid-table-lamp-with-led-bulb-nickel-plated-white__0609332_pe684455_s5.jpg", "supplier_id": 3}

###
PATCH http://localhost:3000/products/10.json
Content-Type: application/json

{ "image_url2": "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/peripherals/input-devices/dell/keyboards/km3322w/media-gallery/keyboard-mouse-km3322w-gallery-1.psd?fmt=pjpg&pscan=auto&scl=1&hei=402&wid=676&qlt=100,0&resMode=sharp2&size=676,402"}

###
DELETE http://localhost:3000/products/22


### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}


### login/session create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{

  "email": "test@test.com",
  "password": "password"

}